baseURL = "https://dylanchiang-dev.github.io/homepage"
title = "My Homepage"
theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Your Name"
  headline = "Welcome to my personal homepage"
  image = "author.jpg"
  links = [
    { github = "https://github.com/yourusername" },
    { email = "mailto:your.email@example.com" },
    { linkedin = "https://linkedin.com/in/yourprofile" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
